/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

function Model(props: any) {
  const { nodes, materials } = useGLTF("/scene.glb");

  useEffect(() => {
    // Adjust the blue color
    if (materials["Eye blue.001"]) {
      materials["Eye blue.001"].color = new THREE.Color("#0000CC"); // Vibrant blue color
    }
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["bodyyyy.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_1.geometry}
        material={materials["Eye blue.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_2.geometry}
        material={materials["Body Wall e.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_3.geometry}
        material={materials["Black rough.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_4.geometry}
        material={materials["Roda.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_5.geometry}
        material={materials["Black roughhh.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_6.geometry}
        material={materials["Head laur.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_7.geometry}
        material={materials["Screen.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_8.geometry}
        material={materials["bodyyyy.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_9.geometry}
        material={materials["SILVER.003"]}
      />
    </group>
  );
}

useGLTF.preload("/scene.glb");

export default Model;
